---
- hosts: localhost
  become: yes
  vars:
    jenkins_hostname: ec2-23-23-41-137.compute-1.amazonaws.com
    docker_users:
    - jenkins
  roles:
    - role: geerlingguy.jenkins
    - role: geerlingguy.docker
