
   - name: add index.html
     file:
          path: /var/www/html/index.html
          state: touch
          owner: root
          group: root
          mode: '0644'

   - name: populate text in index.html
     lineinfile:
          path: /var/www/html/index.html
          line: hello world!
          create: yes

