---
# tasks file for nfs-master-configure
- name: install nfs packages 
  packages:
    name: "{{ item }}"
    state: present
    with_items:
      - nfs-utils
      - rpcbind


- name: Create /tmp/share 
  file:
    path: /tmp/share
    owner: root
    group: root

- name: do not permit traffic in default zone on port 8081/tcp
  firewalld:
    port: 2049/tcp
    permanent: yes
    state: disabled

- name: copy exports.j2 to server
  template:
    src: exports.j2
    dest: /etc/exports
  notify:
    - re-export new shares     

- name: start nfs
  service: 
    name: "{{ item }}" 
    state: restarted
    enabled: yes
  with_item: 
    - nfs-utils
    - rpcbind

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
