---
# tasks file for apache_server=configure
   - name: install apache server
     yum: 
         name: httpd
         state: latest 
       
    

   - name: start and enable apache server
     service: 
        name: httpd 
        state: started 
        enabled: yes 
      

   - name: add index.html
     file:
        path: /var/www/html/index.html
        state: touch
        owner: root
        group: root
        mode: '0644'
  

   - name: populate text in index.html
     lineinfile:
          path: /var/www/html/index.html
          line: hello world!
          create: yes    