---
- hosts: all
  become: true 
  tasks: 
    - name: create new usres 
      user: 
        name : '{{item.name}}'
        uid : '{{item.uid}}'
        state: present 
 
      loop:
        - name: talha 
          uid: 1027
        - name: ibrahim
          uid: 1007
        - name: shadman 
          uid: 1017  

